stages:
  - build
  - deploy

include:
  - project: docker/includes
    file: build-docker.yml
    ref: master
  - project: docker/includes
    file: deploy-docker-compose.yml
    ref: master

deploy-prod:
  extends: .deploy-docker-compose
  stage: deploy
  variables:
    SSH_USER: gitlab
    SSH_HOST: api.byster.ru
    SSH_PORT: 30022
    VHOST_PATH: /srv/byster/website
    DEPLOY_DOCKER_COMPOSE_EXTRA_ARGS: --remove-orphans --no-deps
    DOT_ENV_PATH: $VHOST_PATH/.env
    DOT_ENV: |
      VIRTUAL_HOST=web.byster.ru
      LETSENCRYPT_HOST=web.byster.ru
      LETSENCRYPT_EMAIL=admin@byster.ru
  only:
    - master
